import { TypeDefinition, PropertyInfo, TypeConfig, PropertyPathsPluginOptions } from '../types.js';

/**
 * 将英文复数形式转换为单数形式
 */
function toSingular(word: string): string {
  // 常见的复数转单数规则
  if (word.endsWith('ies') && word.length > 3) {
    return word.slice(0, -3) + 'y';
  }
  if (word.endsWith('es') && word.length > 2) {
    // 检查是否是特定的复数形式
    const specialCases = ['ches', 'shes', 'xes', 'ses'];
    for (const suffix of specialCases) {
      if (word.endsWith(suffix)) {
        return word.slice(0, -2);
      }
    }
    return word.slice(0, -1);
  }
  if (word.endsWith('s') && !word.endsWith('ss') && word.length > 1) {
    return word.slice(0, -1);
  }
  return word;
}

/**
 * 纯函数：从属性路径生成类型名称
 */
export function generateTypeNameFromPath(path: string, typePrefix: string = '', typeSuffix: string = '', isArrayType: boolean = false): string {
  if (!path) {
    return `${typePrefix}${typeSuffix}`;
  }
  
  const segments = path.split('.');
  const lastSegment = segments[segments.length - 1]!;
  
  // 只有当属性名称以`[]`结尾时才进行复数转单数处理
  const singularSegment = isArrayType ? toSingular(lastSegment) : lastSegment;
  const baseName = singularSegment.charAt(0).toUpperCase() + singularSegment.slice(1);
  
  return `${typePrefix}${baseName}${typeSuffix}`;
}

export class TypeGenerator {
  private typeMap = new Map<string, TypeDefinition>();
  private propertyInfo: Record<string, PropertyInfo>;
  private generateComments: boolean;
  private typePrefix: string;
  private typeSuffix: string;

  constructor(private options: PropertyPathsPluginOptions) {
    this.propertyInfo = options.propertyInfo || {};
    this.generateComments = options.generateComments !== false;
    this.typePrefix = options.typePrefix || '';
    this.typeSuffix = options.typeSuffix || '';
  }

  /**
   * 从配置对象生成类型定义
   */
  generateTypeDefinitions(config: TypeConfig, rootTypeName: string, fileName: string): TypeDefinition[] {
    this.typeMap.clear();
    
    const rootType: TypeDefinition = {
      name: rootTypeName,
      properties: {},
      isRoot: true,
      description: '根对象类型',
      fileName
    };
    this.typeMap.set(rootTypeName, rootType);

    this.processConfigObject(config, rootType, '');

    return Array.from(this.typeMap.values());
  }

  /**
   * 递归处理配置对象
   */
  private processConfigObject(config: TypeConfig, parentType: TypeDefinition, parentPath: string): void {
    for (const [key, value] of Object.entries(config)) {
      const currentPath = parentPath ? `${parentPath}.${key}` : key;

      // 检查是否是数组类型（属性名以 [] 结尾）
      const isArrayType = key.endsWith('[]');
      const cleanKey = isArrayType ? key.slice(0, -2) : key;
      const cleanPath = parentPath ? `${parentPath}.${cleanKey}` : cleanKey;

      if (typeof value === 'object' && value !== null) {
        // 创建嵌套类型
        const typeName = this.generateTypeName(cleanPath, isArrayType);
        
        if (!this.typeMap.has(typeName)) {
          const newType: TypeDefinition = {
            name: typeName,
            properties: {},
            description: `${cleanPath} 对象类型`,
            fileName: parentType.fileName
          };
          this.typeMap.set(typeName, newType);
          
          // 如果是数组类型，包装为数组
          parentType.properties[cleanKey] = isArrayType ? `${typeName}[]` : newType;
          
          // 递归处理嵌套对象
          this.processConfigObject(value, newType, cleanPath);
        } else {
          const existingType = this.typeMap.get(typeName);
          if (existingType) {
            // 如果是数组类型，包装为数组
            parentType.properties[cleanKey] = isArrayType ? `${typeName}[]` : existingType;
          }
        }
      } else {
        // 叶子节点，直接设置类型
        const info = this.propertyInfo[currentPath];
        const typeName = info?.type || value;
        
        // 如果是数组类型，包装为数组
        parentType.properties[cleanKey] = isArrayType ? `${typeName}[]` : typeName;
      }
    }
  }

  /**
   * 生成 TypeScript 代码
   */
  generateTypeScriptCode(typeDefs: TypeDefinition[]): string {
    const lines: string[] = [
      '// 自动生成的类型定义 - 请勿手动修改',
      '// Generated by vite-plugin-property-paths-to-types',
      '// https://github.com/cao5zy/vite-plugin-property-paths-to-types\n',
    ];

    // 先定义所有嵌套接口（除了根接口）
    typeDefs
      .filter(type => !type.isRoot)
      .forEach(type => {
        if (this.generateComments && type.description) {
          lines.push(`/** ${type.description} */`);
        }
        lines.push(`export interface ${type.name} {`);
        
        Object.entries(type.properties).forEach(([key, value]) => {
          const typeName = typeof value === 'string' ? value : value.name;
          const propertyPath = this.findPropertyPath(type, key);
          const info = this.propertyInfo[propertyPath];
          
          if (this.generateComments) {
            const commentLines: string[] = [];
            if (info?.description) {
              commentLines.push(` * ${info.description}`);
            }
            if (info?.defaultValue !== undefined) {
              commentLines.push(` * @default ${JSON.stringify(info.defaultValue)}`);
            }
            if (commentLines.length > 0) {
              lines.push('  /**');
              lines.push(...commentLines);
              lines.push('   */');
            }
          }
          
          const required = info?.required !== false;
          const propertyName = required ? key : `${key}?`;
          lines.push(`  ${propertyName}: ${typeName};`);
        });
        
        lines.push('}\n');
      });

    // 最后定义根接口
    const rootType = typeDefs.find(type => type.isRoot);
    if (rootType) {
      if (this.generateComments && rootType.description) {
        lines.push(`/** ${rootType.description} */`);
      }
      lines.push(`export interface ${rootType.name} {`);
      
      Object.entries(rootType.properties).forEach(([key, value]) => {
        const typeName = typeof value === 'string' ? value : value.name;
        const propertyPath = key;
        const info = this.propertyInfo[propertyPath];
        
        if (this.generateComments) {
          const commentLines: string[] = [];
          if (info?.description) {
            commentLines.push(` * ${info.description}`);
          }
          if (info?.defaultValue !== undefined) {
            commentLines.push(` * @default ${JSON.stringify(info.defaultValue)}`);
          }
          if (commentLines.length > 0) {
            lines.push('  /**');
            lines.push(...commentLines);
            lines.push('   */');
          }
        }
        
        const required = info?.required !== false;
        const propertyName = required ? key : `${key}?`;
          lines.push(`  ${propertyName}: ${typeName};`);
      });
      
      lines.push('}');
    }

    return lines.join('\n');
  }

  /**
   * 生成类型名称
   */
  private generateTypeName(path: string, isArrayType: boolean = false): string {
    return generateTypeNameFromPath(path, this.typePrefix, this.typeSuffix, isArrayType);
  }

  /**
   * 查找属性路径
   */
  private findPropertyPath(type: TypeDefinition, key: string): string {
    // 简化实现，实际中可能需要更复杂的路径查找
    for (const [fullPath, info] of Object.entries(this.propertyInfo)) {
      const pathSegments = fullPath.split('.');
      const lastSegment = pathSegments.pop();
      if (lastSegment === key) {
        return fullPath;
      }
    }
    return key;
  }

  /**
   * 获取生成的类型名称
   */
  getGeneratedTypeNames(): string[] {
    return Array.from(this.typeMap.keys());
  }
}
